import { assert, test } from '@codemod-utils/tests';

import { inYaml } from '../../../../../src/utils/analyze-project/find-available-keys/index.js';

test('utils | analyze-project | find-available-keys | in-yaml > base case', function () {
  const file = [
    `components.products.product.card.learn-more.aria-label: Learn more about {productName}`,
    `components.products.product.card.learn-more.label: Learn more`,
    `components.products.product.details.add-to-cart: Add to Cart`,
    `components.products.product.details.description: Description`,
    `components.products.product.details.price: Price`,
    `components.products.product.details.rating: Rating`,
    `components.products.product.details.rating-value: "{productRating} out of 5 stars"`,
    `components.products.product.details.seller: Seller`,
    `routes.application.app-name: Ember Workshop`,
    `routes.application.copyright: 'Created by <a href="https://www.linkedin.com/in/ijlee2/" rel="noopener noreferrer" target="_blank">Isaac J. Lee</a> © 2025'`,
    `routes.application.navigation-menu:`,
    `routes.application.navigation-menu.name: Main Navigation`,
    `routes.application.navigation-menu.routes:`,
    `routes.application.navigation-menu.routes.form: Form`,
    `routes.application.navigation-menu.routes.index: Home`,
    `routes.application.navigation-menu.routes.products: Products`,
    `routes.application.navigation-text: The page navigation is complete. You may now navigate the page content as you wish.`,
    `routes.application.skip-text: Skip to main content`,
    `routes.error.default-message: Something went wrong.`,
    `routes.form.title: Form`,
    `routes.form.contact-me-form.fields.donation.label: Donation amount ($)`,
    `routes.form.contact-me-form.fields.donation.placeholder: "100"`,
    `routes.form.contact-me-form.fields.email.label: Email`,
    `routes.form.contact-me-form.fields.email.placeholder: zoey@emberjs.com`,
    `routes.form.contact-me-form.fields.message.label: Message`,
    `routes.form.contact-me-form.fields.message.placeholder:`,
    `routes.form.contact-me-form.fields.name.label: Name`,
    `routes.form.contact-me-form.fields.name.placeholder: Zoey`,
    `routes.form.contact-me-form.fields.subscribe.label: Subscribe to The Ember Times?`,
    `routes.form.contact-me-form.fields.subscribe.placeholder:`,
    `routes.form.contact-me-form.instructions: Still have questions about ember-container-query? Try sending me a message.`,
    `routes.form.contact-me-form.title: Contact me`,
    `routes.index.description: 'To see what you can do with <a href="https://emberjs.com/" target="_blank" rel="noopener noreferrer">Ember.js</a>, visit one of the examples in the main navigation.'`,
    `routes.index.title: Ember Workshop`,
    `routes.product-details.back: See all products`,
    `routes.product-details.title: Product Details`,
    `routes.products.filter-by.name.label: Filter by name`,
    `routes.products.filter-by.name.placeholder: Cake, pasta, etc.`,
    `routes.products.no-products-found: No products found.`,
    `routes.products.sort-by.label: Sort by`,
    `routes.products.sort-by.name-ascending: "Name: A to Z"`,
    `routes.products.sort-by.name-descending: "Name: Z to A"`,
    `routes.products.sort-by.price-ascending: "Price: Low to High"`,
    `routes.products.sort-by.price-descending: "Price: High to Low"`,
    `routes.products.title: Products`,
    ``,
  ].join('\n');

  const keys = inYaml(file);

  assert.deepStrictEqual(keys, [
    'components.products.product.card.learn-more.aria-label',
    'components.products.product.card.learn-more.label',
    'components.products.product.details.add-to-cart',
    'components.products.product.details.description',
    'components.products.product.details.price',
    'components.products.product.details.rating',
    'components.products.product.details.rating-value',
    'components.products.product.details.seller',
    'routes.application.app-name',
    'routes.application.copyright',
    'routes.application.navigation-menu.name',
    'routes.application.navigation-menu.routes.form',
    'routes.application.navigation-menu.routes.index',
    'routes.application.navigation-menu.routes.products',
    'routes.application.navigation-text',
    'routes.application.skip-text',
    'routes.error.default-message',
    'routes.form.title',
    'routes.form.contact-me-form.fields.donation.label',
    'routes.form.contact-me-form.fields.donation.placeholder',
    'routes.form.contact-me-form.fields.email.label',
    'routes.form.contact-me-form.fields.email.placeholder',
    'routes.form.contact-me-form.fields.message.label',
    'routes.form.contact-me-form.fields.name.label',
    'routes.form.contact-me-form.fields.name.placeholder',
    'routes.form.contact-me-form.fields.subscribe.label',
    'routes.form.contact-me-form.instructions',
    'routes.form.contact-me-form.title',
    'routes.index.description',
    'routes.index.title',
    'routes.product-details.back',
    'routes.product-details.title',
    'routes.products.filter-by.name.label',
    'routes.products.filter-by.name.placeholder',
    'routes.products.no-products-found',
    'routes.products.sort-by.label',
    'routes.products.sort-by.name-ascending',
    'routes.products.sort-by.name-descending',
    'routes.products.sort-by.price-ascending',
    'routes.products.sort-by.price-descending',
    'routes.products.title',
  ]);
});
