template: |
  ## 🗞 What’s Changed

  $CHANGES

categories:
  - label: "breaking"
    title: Breaking Change
  - label: "bug"
    title: Bug Fix
  - label: "enhance: code"
    title: Enhancement
  - label: "enhance: dependency"
    title: Internal
  - label: "enhance: documentation"
    title: Documentation
