template: |
  ## 🗞 What’s Changed

  $CHANGES

categories:
  - label: feature
    title: 🚀 Features
  - label: fix
    title: 🐛 Bug Fixes
  - label: docs
    title: 📖 Documentation
  - label: test
    title: 🧪 Tests
  - label: chore
    title: 🧹 Housekeeping

