import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { inJsTs } from '../../../../../src/utils/analyze-project/find-used-keys/index.js';

test('utils | analyze-project | find-used-keys | in-ts > component (3)', function () {
  const file = normalizeFile([
    `import { type Registry as Services, service } from '@ember/service';`,
    `import Component from '@glimmer/component';`,
    `import { tKey } from 'ember-intl';`,
    ``,
    `interface HelloSignature {`,
    `  Args: {};`,
    `}`,
    ``,
    `export default class Hello extends Component<HelloSignature> {`,
    `  @service declare intl: Services['intl'];`,
    ``,
    `  get getter01(): string {`,
    `    return this.intl.t('key01');`,
    `  }`,
    ``,
    `  get getter02(): string {`,
    `    return this.intl.t(\`key02\`);`,
    `  }`,
    ``,
    `  get getter03(): string {`,
    `    return this.someCondition ? this.intl.t('key03') : this.intl.t('key04');`,
    `  }`,
    ``,
    `  get getter04(): string {`,
    `    return this.intl.t(`,
    `      this.someCondition ? 'key05' : 'key06'`,
    `    );`,
    `  }`,
    ``,
    `  get getter05(): string {`,
    `    const key = this.someCondition ? 'key07' : 'key08';`,
    `    return this.intl.t(key);`,
    `  }`,
    ``,
    `  get getter06(): string {`,
    `    const key = this.someCondition ? tKey('key09') : tKey('key10');`,
    `    return this.intl.t(key);`,
    `  }`,
    ``,
    `  get getter07(): string {`,
    `    const key = 'key11';`,
    `    return this.intl.t(key);`,
    `  }`,
    ``,
    `  get getter08(): string {`,
    `    const key = tKey('key12');`,
    `    return this.intl.t(key);`,
    `  }`,
    ``,
    `  get getter09(): string {`,
    `    const key = tKey(\`key13\`);`,
    `    return this.intl.t(key);`,
    `  }`,
    ``,
    `  get getter10(): string {`,
    `    const key = tKey(\`key14.\${'some-key'}\`);`,
    `    return this.intl.t(key);`,
    `  }`,
    ``,
    `  get getter11(): string {`,
    `    const key = 'some-key';`,
    `    return this.intl.t(\`key15.\${key}\`);`,
    `  }`,
    `}`,
    ``,
  ]);

  const keys = inJsTs(file, {
    isTypeScript: true,
  });

  assert.deepStrictEqual(keys, [
    'key01',
    'key02',
    'key03',
    'key04',
    'key05',
    'key06',
    'key09',
    'key10',
    'key12',
    'key13',
  ]);
});
