/*jslint eqeq: true*/

// GENERATED FILE, DO NOT COPY INTO PROJECT
// THIS IS SOLELY FOR THE DUMMY APP SINCE IT
// DOES NOT GO THROUGH THE BROCCOLI PLUGIN
// WHICH PARSES OUT THE CLDR DATA BELOW
export default {
    locale: "en-US",
    parentLocale: "en"
};
