import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { inGjsGts } from '../../../../../src/utils/analyze-project/find-used-keys/index.js';

test('utils | analyze-project | find-used-keys | in-gts > edge case (1)', function () {
  const file = normalizeFile([
    `import { type Registry as Services, service } from '@ember/service';`,
    `import Component from '@glimmer/component';`,
    `import { tKey as t } from 'ember-intl';`,
    ``,
    `interface HelloSignature {`,
    `  Args: {};`,
    `}`,
    ``,
    `export default class Hello extends Component<HelloSignature> {`,
    `  @service('intl') declare x: Services['intl'];`,
    ``,
    `  get getter01(): string {`,
    `    return this.x.t('key01');`,
    `  }`,
    ``,
    `  get getter02(): string {`,
    `    return this.x.t(\`key02\`);`,
    `  }`,
    ``,
    `  get getter03(): string {`,
    `    return this.someCondition ? this.x.t('key03') : this.x.t('key04');`,
    `  }`,
    ``,
    `  get getter04(): string {`,
    `    return this.x.t(`,
    `      this.someCondition ? 'key05' : 'key06'`,
    `    );`,
    `  }`,
    ``,
    `  get getter05(): string {`,
    `    const key = this.someCondition ? 'key07' : 'key08';`,
    `    return this.x.t(key);`,
    `  }`,
    ``,
    `  get getter06(): string {`,
    `    const key = this.someCondition ? t('key09') : t('key10');`,
    `    return this.x.t(key);`,
    `  }`,
    ``,
    `  get getter07(): string {`,
    `    const key = 'key11';`,
    `    return this.x.t(key);`,
    `  }`,
    ``,
    `  get getter08(): string {`,
    `    const key = t('key12');`,
    `    return this.x.t(key);`,
    `  }`,
    ``,
    `  get getter09(): string {`,
    `    const key = t(\`key13\`);`,
    `    return this.x.t(key);`,
    `  }`,
    ``,
    `  get getter10(): string {`,
    `    const key = t(\`key14.\${'some-key'}\`);`,
    `    return this.x.t(key);`,
    `  }`,
    ``,
    `  get getter11(): string {`,
    `    const key = 'some-key';`,
    `    return this.x.t(\`key15.\${key}\`);`,
    `  }`,
    ``,
    `  <template></template>`,
    `}`,
    ``,
  ]);

  const keys = inGjsGts(file, {
    isTypeScript: true,
  });

  assert.deepStrictEqual(keys, [
    'key01',
    'key02',
    'key03',
    'key04',
    'key05',
    'key06',
    'key09',
    'key10',
    'key12',
    'key13',
  ]);
});
