import { assert, normalizeFile, test } from '@codemod-utils/tests';

import { inHbs } from '../../../../../src/utils/analyze-project/find-used-keys/index.js';

test('utils | analyze-project | find-used-keys | in-hbs > with unless helper', function () {
  const file = normalizeFile([
    `{{unless this.someCondition "key01"}}`,
    ``,
    `{{unless this.someCondition (t "key02")}}`,
    ``,
    `{{unless this.someCondition (t "key03") (t "key04")}}`,
    ``,
    `{{unless this.someCondition`,
    `  (t "key05")`,
    `  (unless this.someCondition2 (t "key06") (t "key07"))`,
    `}}`,
    ``,
    `{{unless this.someCondition`,
    `  (t "key08")`,
    `  (unless this.someCondition2 (t "key09") (t "key10"))`,
    `}}`,
    ``,
    `{{t (unless this.someCondition "key11" "key12")}}`,
    ``,
    `{{t`,
    `  (unless`,
    `    this.someCondition`,
    `    "key13"`,
    `    (unless this.someCondition2 "key14" "key15")`,
    `  )`,
    `}}`,
    ``,
    `{{t`,
    `  (unless`,
    `    this.someCondition`,
    `    (unless this.someCondition2 "key16" "key17")`,
    `    "key18"`,
    `  )`,
    `}}`,
    ``,
    `{{t-key (unless this.someCondition "key19" "key20")}}`,
    ``,
    `{{t`,
    `  (t-key`,
    `    (unless`,
    `      this.someCondition`,
    `      "key21"`,
    `      (unless this.someCondition2 "key22" "key23")`,
    `    )`,
    `  )`,
    `}}`,
    ``,
    `{{t`,
    `  (t-key`,
    `    (unless`,
    `      this.someCondition`,
    `      (unless this.someCondition2 "key24" "key25")`,
    `      "key26"`,
    `    )`,
    `  )`,
    `}}`,
  ]);

  const keys = inHbs(file);

  assert.deepStrictEqual(keys, [
    'key02',
    'key03',
    'key04',
    'key05',
    'key06',
    'key07',
    'key08',
    'key09',
    'key10',
    'key11',
    'key12',
    'key13',
    'key14',
    'key15',
    'key16',
    'key17',
    'key18',
    'key19',
    'key20',
    'key21',
    'key22',
    'key23',
    'key24',
    'key25',
    'key26',
  ]);
});
