import { assert, test } from '@codemod-utils/tests';

import { inHbs } from '../../../../../src/utils/analyze-project/find-used-keys/index.js';

test('utils | analyze-project | find-used-keys | in-hbs > with if helper', function () {
  const file = [
    `{{if this.someCondition "key01"}}`,
    ``,
    `{{if this.someCondition (t "key02")}}`,
    ``,
    `{{if this.someCondition (t "key03") (t "key04")}}`,
    ``,
    `{{if this.someCondition`,
    `  (t "key05")`,
    `  (if this.someCondition2 (t "key06") (t "key07"))`,
    `}}`,
    ``,
    `{{if this.someCondition`,
    `  (t "key08")`,
    `  (if this.someCondition2 (t "key09") (t "key10"))`,
    `}}`,
    ``,
    `{{t (if this.someCondition "key11" "key12")}}`,
    ``,
    `{{t`,
    `  (if`,
    `    this.someCondition`,
    `    "key13"`,
    `    (if this.someCondition2 "key14" "key15")`,
    `  )`,
    `}}`,
    ``,
    `{{t`,
    `  (if`,
    `    this.someCondition`,
    `    (if this.someCondition2 "key16" "key17")`,
    `    "key18"`,
    `  )`,
    `}}`,
    ``,
    `{{t-key (if this.someCondition "key19" "key20")}}`,
    ``,
    `{{t`,
    `  (t-key`,
    `    (if`,
    `      this.someCondition`,
    `      "key21"`,
    `      (if this.someCondition2 "key22" "key23")`,
    `    )`,
    `  )`,
    `}}`,
    ``,
    `{{t`,
    `  (t-key`,
    `    (if`,
    `      this.someCondition`,
    `      (if this.someCondition2 "key24" "key25")`,
    `      "key26"`,
    `    )`,
    `  )`,
    `}}`,
  ].join('\n');

  const keys = inHbs(file);

  assert.deepStrictEqual(keys, [
    'key02',
    'key03',
    'key04',
    'key05',
    'key06',
    'key07',
    'key08',
    'key09',
    'key10',
    'key11',
    'key12',
    'key13',
    'key14',
    'key15',
    'key16',
    'key17',
    'key18',
    'key19',
    'key20',
    'key21',
    'key22',
    'key23',
    'key24',
    'key25',
    'key26',
  ]);
});
