name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-location:
          - 'docs/my-v1-addon'
          - 'docs/my-v1-app'
          - 'docs/my-v1-app-with-fallbacks'
          - 'docs/my-v1-app-with-lazy-loaded-translations'
          - 'docs/my-v1-app-with-namespace-from-folders'
          - 'docs/my-v1-classic-app'
          - 'docs/my-v1-classic-app-with-lazy-loaded-translations'
          - 'docs/my-v1-engine'
          - 'docs/my-v2-addon'
          - 'docs/my-v2-app'
          - 'docs/my-v2-app-with-fallbacks'
          - 'docs/my-v2-app-with-lazy-loaded-translations'
          - 'docs/my-v2-app-with-namespace-from-folders'
          - 'packages/ember-intl-lint'
          - 'packages/ember-intl-v1-compat'
          - 'packages/ember-intl-vite'
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test
        working-directory: ${{ matrix.package-location }}
