name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

env:
  NODE_VERSION: 22

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-location:
          - 'tests/ember-intl'
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test
        working-directory: ${{ matrix.package-location }}


  get-test-matrix:
    name: Get test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-test-matrix.outputs.matrix }}
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - id: set-test-matrix
        name: Set test matrix
        run: echo "matrix=$(pnpx @embroider/try list)" >> $GITHUB_OUTPUT
        working-directory: 'tests/ember-intl'


  test-compatibility:
    name: Test compatibility
    needs: [get-test-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-test-matrix.outputs.matrix) }}
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          cache: 'pnpm'
          node-version: ${{ env.NODE_VERSION }}

      - name: Make file changes
        run: pnpx @embroider/try apply ${{ matrix.name }}
        working-directory: 'tests/ember-intl'

      - name: Install dependencies
        run: pnpm install --no-lockfile

      - name: Test
        env: ${{ matrix.env }}
        run: pnpm test
        working-directory: 'tests/ember-intl'
